//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::Address;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CronJobV0 {
pub discriminator: [u8; 8],
pub id: u32,
pub user_cron_jobs: Address,
pub task_queue: Address,
pub authority: Address,
pub free_tasks_per_transaction: u8,
pub num_tasks_per_queue_call: u8,
pub schedule: String,
pub name: String,
pub current_exec_ts: i64,
pub current_transaction_id: u32,
pub num_transactions: u32,
pub next_transaction_id: u32,
pub removed_from_queue: bool,
pub bump_seed: u8,
pub next_schedule_task: Address,
}


pub const CRON_JOB_V0_DISCRIMINATOR: [u8; 8] = [69, 161, 189, 23, 250, 59, 67, 157];

impl CronJobV0 {
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for CronJobV0 {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_cron_job_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::cron_client::shared::DecodedAccount<CronJobV0>, std::io::Error> {
  let accounts = fetch_all_cron_job_v0(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_cron_job_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::cron_client::shared::DecodedAccount<CronJobV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::cron_client::shared::DecodedAccount<CronJobV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::other(format!("Account not found: {address}")))?;
      let data = CronJobV0::from_bytes(&account.data)?;
      decoded_accounts.push(crate::cron_client::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_cron_job_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::cron_client::shared::MaybeAccount<CronJobV0>, std::io::Error> {
    let accounts = fetch_all_maybe_cron_job_v0(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_cron_job_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::cron_client::shared::MaybeAccount<CronJobV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::cron_client::shared::MaybeAccount<CronJobV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = CronJobV0::from_bytes(&account.data)?;
        decoded_accounts.push(crate::cron_client::shared::MaybeAccount::Exists(crate::cron_client::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::cron_client::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for CronJobV0 {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for CronJobV0 {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for CronJobV0 {
      fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(
          crate::cron_client::CRON_ID.to_bytes()
        )
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for CronJobV0 {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for CronJobV0 {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

