//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::Address;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct UserCronJobsV0 {
pub discriminator: [u8; 8],
pub authority: Address,
pub min_cron_job_id: u32,
pub next_cron_job_id: u32,
pub bump_seed: u8,
}


pub const USER_CRON_JOBS_V0_DISCRIMINATOR: [u8; 8] = [62, 38, 165, 254, 98, 211, 89, 60];

impl UserCronJobsV0 {
      pub const LEN: usize = 49;
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for UserCronJobsV0 {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_user_cron_jobs_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::cron_client::shared::DecodedAccount<UserCronJobsV0>, std::io::Error> {
  let accounts = fetch_all_user_cron_jobs_v0(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_user_cron_jobs_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::cron_client::shared::DecodedAccount<UserCronJobsV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::cron_client::shared::DecodedAccount<UserCronJobsV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::other(format!("Account not found: {address}")))?;
      let data = UserCronJobsV0::from_bytes(&account.data)?;
      decoded_accounts.push(crate::cron_client::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_user_cron_jobs_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::cron_client::shared::MaybeAccount<UserCronJobsV0>, std::io::Error> {
    let accounts = fetch_all_maybe_user_cron_jobs_v0(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_user_cron_jobs_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::cron_client::shared::MaybeAccount<UserCronJobsV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::cron_client::shared::MaybeAccount<UserCronJobsV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = UserCronJobsV0::from_bytes(&account.data)?;
        decoded_accounts.push(crate::cron_client::shared::MaybeAccount::Exists(crate::cron_client::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::cron_client::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for UserCronJobsV0 {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for UserCronJobsV0 {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for UserCronJobsV0 {
      fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(
          crate::cron_client::CRON_ID.to_bytes()
        )
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for UserCronJobsV0 {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for UserCronJobsV0 {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

