//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::Address;
use crate::tuktuk_client::types::CompiledInstructionV0;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct CompiledTransactionV0 {
pub num_rw_signers: u8,
pub num_ro_signers: u8,
pub num_rw: u8,
pub accounts: Vec<Address>,
pub instructions: Vec<CompiledInstructionV0>,
/// Additional signer seeds. Should include bump. Useful for things like initializing a mint where
/// you cannot pass a keypair.
/// Note that these seeds will be prefixed with "custom", task_queue.key
/// and the bump you pass and account should be consistent with this. But to save space
/// in the instruction, they should be ommitted here. See tests for examples
pub signer_seeds: Vec<Vec<Vec<u8>>>,
}


