//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::tuktuk_client::types::TriggerV0;
use crate::tuktuk_client::types::TransactionSourceV0;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct TaskReturnV0 {
pub trigger: TriggerV0,
pub transaction: TransactionSourceV0,
pub crank_reward: Option<u64>,
pub free_tasks: u8,
pub description: String,
}


