//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::cron_client::types::TaskReturnV0;
use solana_address::Address;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct RunTaskReturnV0 {
pub tasks: Vec<TaskReturnV0>,
pub accounts: Vec<Address>,
}


