[toolchain]
anchor_version = "1.0.0"
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mock_pyth = "8tmS6MDh3CBo82p8FwoeJmXrMawGUca7uMPAkUbKeVPW"
put_swap = "6Jrrf5D51rEdUQwfX5XTgyy4L36VMp7QuZp22wn1P5fb"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
