//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub mod accounts;
        // `errors` is suppressed: codama-generated error enums pull in
        // `num_derive` and `thiserror`, which we don't need onchain. Errors
        // returned by the cron program will still surface as standard
        // `ProgramError::Custom(code)` to the runtime.
        // pub mod errors;
        pub mod instructions;
        pub mod programs;
        pub mod shared;
        pub mod types;
  
  pub(crate) use programs::*;
