//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::{address, Address};


  /// `cron` program ID.
  pub const CRON_ID: Address = address!("cronAjRZnJn3MTP3B9kE62NWDrjSuAPVXf9c4hu4grM");

