//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum CronError {
    /// 6000 - Invalid schedule
    #[error("Invalid schedule")]
    InvalidSchedule = 0x1770,
    /// 6001 - Transaction already exists
    #[error("Transaction already exists")]
    TransactionAlreadyExists = 0x1771,
    /// 6002 - Insufficient funds
    #[error("Insufficient funds")]
    InsufficientFunds = 0x1772,
    /// 6003 - Overflow
    #[error("Overflow")]
    Overflow = 0x1773,
    /// 6004 - Invalid data increase
    #[error("Invalid data increase")]
    InvalidDataIncrease = 0x1774,
    /// 6005 - Cron job has transactions
    #[error("Cron job has transactions")]
    CronJobHasTransactions = 0x1775,
    /// 6006 - Invalid number of tasks per queue call
    #[error("Invalid number of tasks per queue call")]
    InvalidNumTasksPerQueueCall = 0x1776,
    /// 6007 - Too early to queue tasks
    #[error("Too early to queue tasks")]
    TooEarly = 0x1777,
}

impl From<CronError> for solana_program_error::ProgramError {
    fn from(e: CronError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

