//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use num_derive::FromPrimitive;
use thiserror::Error;

#[derive(Clone, Debug, Eq, Error, FromPrimitive, PartialEq)]
pub enum TuktukError {
    /// 6000 - Task already exists
    #[error("Task already exists")]
    TaskAlreadyExists = 0x1770,
    /// 6001 - Signer account mismatched account in definition
    #[error("Signer account mismatched account in definition")]
    InvalidSigner = 0x1771,
    /// 6002 - Writable account mismatched account in definition
    #[error("Writable account mismatched account in definition")]
    InvalidWritable = 0x1772,
    /// 6003 - Account mismatched account in definition
    #[error("Account mismatched account in definition")]
    InvalidAccount = 0x1773,
    /// 6004 - Invalid data increase
    #[error("Invalid data increase")]
    InvalidDataIncrease = 0x1774,
    /// 6005 - Task not ready
    #[error("Task not ready")]
    TaskNotReady = 0x1775,
    /// 6006 - Task queue not empty
    #[error("Task queue not empty")]
    TaskQueueNotEmpty = 0x1776,
    /// 6007 - Free task account not empty
    #[error("Free task account not empty")]
    FreeTaskAccountNotEmpty = 0x1777,
    /// 6008 - Invalid task PDA
    #[error("Invalid task PDA")]
    InvalidTaskPDA = 0x1778,
    /// 6009 - Task queue insufficient funds
    #[error("Task queue insufficient funds")]
    TaskQueueInsufficientFunds = 0x1779,
    /// 6010 - Sig verification failed
    #[error("Sig verification failed")]
    SigVerificationFailed = 0x177A,
    /// 6011 - Invalid transaction source
    #[error("Invalid transaction source")]
    InvalidTransactionSource = 0x177B,
    /// 6012 - Invalid task verification hash
    #[error("Invalid task verification hash")]
    InvalidVerificationAccountsHash = 0x177C,
    /// 6013 - Invalid rent refund
    #[error("Invalid rent refund")]
    InvalidRentRefund = 0x177D,
    /// 6014 - Invalid task id
    #[error("Invalid task id")]
    InvalidTaskId = 0x177E,
    /// 6015 - Don't use the dummy instruction
    #[error("Don't use the dummy instruction")]
    DummyInstruction = 0x177F,
    /// 6016 - Invalid description length
    #[error("Invalid description length")]
    InvalidDescriptionLength = 0x1780,
    /// 6017 - Task queue has queue authorities
    #[error("Task queue has queue authorities")]
    TaskQueueHasQueueAuthorities = 0x1781,
}

impl From<TuktukError> for solana_program_error::ProgramError {
    fn from(e: TuktukError) -> Self {
        solana_program_error::ProgramError::Custom(e as u32)
    }
}

