//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLOSE_TASK_QUEUE_V0_DISCRIMINATOR: [u8; 8] = [196, 228, 35, 71, 131, 69, 175, 176];

/// Accounts.
#[derive(Debug)]
pub struct CloseTaskQueueV0 {
      
              
          pub rent_refund: solana_address::Address,
          
              
          pub payer: solana_address::Address,
          
              
          pub update_authority: solana_address::Address,
          
              
          pub tuktuk_config: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
          
              
          pub task_queue_name_mapping: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
      }

impl CloseTaskQueueV0 {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(7+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.update_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.tuktuk_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue_name_mapping,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = CloseTaskQueueV0InstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct CloseTaskQueueV0InstructionData {
            discriminator: [u8; 8],
      }

impl CloseTaskQueueV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [196, 228, 35, 71, 131, 69, 175, 176],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for CloseTaskQueueV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `CloseTaskQueueV0`.
///
/// ### Accounts:
///
                ///   0. `[writable]` rent_refund
                      ///   1. `[writable, signer]` payer
                ///   2. `[signer]` update_authority
                ///   3. `[writable]` tuktuk_config
                ///   4. `[writable]` task_queue
                ///   5. `[writable]` task_queue_name_mapping
                ///   6. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CloseTaskQueueV0Builder {
            rent_refund: Option<solana_address::Address>,
                payer: Option<solana_address::Address>,
                update_authority: Option<solana_address::Address>,
                tuktuk_config: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                task_queue_name_mapping: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CloseTaskQueueV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            #[inline(always)]
    pub fn update_authority(&mut self, update_authority: solana_address::Address) -> &mut Self {
                        self.update_authority = Some(update_authority);
                    self
    }
            #[inline(always)]
    pub fn tuktuk_config(&mut self, tuktuk_config: solana_address::Address) -> &mut Self {
                        self.tuktuk_config = Some(tuktuk_config);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            #[inline(always)]
    pub fn task_queue_name_mapping(&mut self, task_queue_name_mapping: solana_address::Address) -> &mut Self {
                        self.task_queue_name_mapping = Some(task_queue_name_mapping);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = CloseTaskQueueV0 {
                              rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        payer: self.payer.expect("payer is not set"),
                                        update_authority: self.update_authority.expect("update_authority is not set"),
                                        tuktuk_config: self.tuktuk_config.expect("tuktuk_config is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                                        task_queue_name_mapping: self.task_queue_name_mapping.expect("task_queue_name_mapping is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `close_task_queue_v0` CPI accounts.
  pub struct CloseTaskQueueV0CpiAccounts<'a, 'b> {
          
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub update_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub tuktuk_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue_name_mapping: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `close_task_queue_v0` CPI instruction.
pub struct CloseTaskQueueV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub update_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub tuktuk_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue_name_mapping: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> CloseTaskQueueV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: CloseTaskQueueV0CpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              rent_refund: accounts.rent_refund,
              payer: accounts.payer,
              update_authority: accounts.update_authority,
              tuktuk_config: accounts.tuktuk_config,
              task_queue: accounts.task_queue,
              task_queue_name_mapping: accounts.task_queue_name_mapping,
              system_program: accounts.system_program,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(7+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.update_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.tuktuk_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue_name_mapping.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = CloseTaskQueueV0InstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(8 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.payer.clone());
                        account_infos.push(self.update_authority.clone());
                        account_infos.push(self.tuktuk_config.clone());
                        account_infos.push(self.task_queue.clone());
                        account_infos.push(self.task_queue_name_mapping.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `CloseTaskQueueV0` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` rent_refund
                      ///   1. `[writable, signer]` payer
                ///   2. `[signer]` update_authority
                ///   3. `[writable]` tuktuk_config
                ///   4. `[writable]` task_queue
                ///   5. `[writable]` task_queue_name_mapping
          ///   6. `[]` system_program
#[derive(Clone, Debug)]
pub struct CloseTaskQueueV0CpiBuilder<'a, 'b> {
  instruction: Box<CloseTaskQueueV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CloseTaskQueueV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(CloseTaskQueueV0CpiBuilderInstruction {
      __program: program,
              rent_refund: None,
              payer: None,
              update_authority: None,
              tuktuk_config: None,
              task_queue: None,
              task_queue_name_mapping: None,
              system_program: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      #[inline(always)]
    pub fn update_authority(&mut self, update_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.update_authority = Some(update_authority);
                    self
    }
      #[inline(always)]
    pub fn tuktuk_config(&mut self, tuktuk_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.tuktuk_config = Some(tuktuk_config);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
      #[inline(always)]
    pub fn task_queue_name_mapping(&mut self, task_queue_name_mapping: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue_name_mapping = Some(task_queue_name_mapping);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = CloseTaskQueueV0Cpi {
        __program: self.instruction.__program,
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          update_authority: self.instruction.update_authority.expect("update_authority is not set"),
                  
          tuktuk_config: self.instruction.tuktuk_config.expect("tuktuk_config is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                  
          task_queue_name_mapping: self.instruction.task_queue_name_mapping.expect("task_queue_name_mapping is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct CloseTaskQueueV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                update_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                tuktuk_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue_name_mapping: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

