//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const DEQUEUE_TASK_V0_DISCRIMINATOR: [u8; 8] = [92, 141, 249, 132, 219, 109, 215, 126];

/// Accounts.
#[derive(Debug)]
pub struct DequeueTaskV0 {
      
              
          pub queue_authority: solana_address::Address,
          
              
          pub rent_refund: solana_address::Address,
          
              
          pub task_queue_authority: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
          
              
          pub task: solana_address::Address,
      }

impl DequeueTaskV0 {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.queue_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.task_queue_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = DequeueTaskV0InstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct DequeueTaskV0InstructionData {
            discriminator: [u8; 8],
      }

impl DequeueTaskV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [92, 141, 249, 132, 219, 109, 215, 126],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for DequeueTaskV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `DequeueTaskV0`.
///
/// ### Accounts:
///
                ///   0. `[signer]` queue_authority
                ///   1. `[writable]` rent_refund
          ///   2. `[]` task_queue_authority
                ///   3. `[writable]` task_queue
                ///   4. `[writable]` task
#[derive(Clone, Debug, Default)]
pub struct DequeueTaskV0Builder {
            queue_authority: Option<solana_address::Address>,
                rent_refund: Option<solana_address::Address>,
                task_queue_authority: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                task: Option<solana_address::Address>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl DequeueTaskV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: solana_address::Address) -> &mut Self {
                        self.queue_authority = Some(queue_authority);
                    self
    }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: solana_address::Address) -> &mut Self {
                        self.task_queue_authority = Some(task_queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            #[inline(always)]
    pub fn task(&mut self, task: solana_address::Address) -> &mut Self {
                        self.task = Some(task);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = DequeueTaskV0 {
                              queue_authority: self.queue_authority.expect("queue_authority is not set"),
                                        rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        task_queue_authority: self.task_queue_authority.expect("task_queue_authority is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                                        task: self.task.expect("task is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `dequeue_task_v0` CPI accounts.
  pub struct DequeueTaskV0CpiAccounts<'a, 'b> {
          
                    
              pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task: &'b solana_account_info::AccountInfo<'a>,
            }

/// `dequeue_task_v0` CPI instruction.
pub struct DequeueTaskV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> DequeueTaskV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: DequeueTaskV0CpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              queue_authority: accounts.queue_authority,
              rent_refund: accounts.rent_refund,
              task_queue_authority: accounts.task_queue_authority,
              task_queue: accounts.task_queue,
              task: accounts.task,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.queue_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.task_queue_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = DequeueTaskV0InstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.queue_authority.clone());
                        account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.task_queue_authority.clone());
                        account_infos.push(self.task_queue.clone());
                        account_infos.push(self.task.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `DequeueTaskV0` via CPI.
///
/// ### Accounts:
///
                ///   0. `[signer]` queue_authority
                ///   1. `[writable]` rent_refund
          ///   2. `[]` task_queue_authority
                ///   3. `[writable]` task_queue
                ///   4. `[writable]` task
#[derive(Clone, Debug)]
pub struct DequeueTaskV0CpiBuilder<'a, 'b> {
  instruction: Box<DequeueTaskV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DequeueTaskV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(DequeueTaskV0CpiBuilderInstruction {
      __program: program,
              queue_authority: None,
              rent_refund: None,
              task_queue_authority: None,
              task_queue: None,
              task: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.queue_authority = Some(queue_authority);
                    self
    }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue_authority = Some(task_queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
      #[inline(always)]
    pub fn task(&mut self, task: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task = Some(task);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = DequeueTaskV0Cpi {
        __program: self.instruction.__program,
                  
          queue_authority: self.instruction.queue_authority.expect("queue_authority is not set"),
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          task_queue_authority: self.instruction.task_queue_authority.expect("task_queue_authority is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                  
          task: self.instruction.task.expect("task is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct DequeueTaskV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                task: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

