//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const INITIALIZE_TUKTUK_CONFIG_V0_DISCRIMINATOR: [u8; 8] = [67, 128, 98, 227, 103, 60, 179, 214];

/// Accounts.
#[derive(Debug)]
pub struct InitializeTuktukConfigV0 {
      
              
          pub payer: solana_address::Address,
          
              
          pub approver: solana_address::Address,
          
              
          pub authority: solana_address::Address,
          
              
          pub tuktuk_config: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
      }

impl InitializeTuktukConfigV0 {
  pub fn instruction(&self, args: InitializeTuktukConfigV0InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitializeTuktukConfigV0InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.approver,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.tuktuk_config,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = InitializeTuktukConfigV0InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct InitializeTuktukConfigV0InstructionData {
            discriminator: [u8; 8],
            }

impl InitializeTuktukConfigV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [67, 128, 98, 227, 103, 60, 179, 214],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for InitializeTuktukConfigV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct InitializeTuktukConfigV0InstructionArgs {
                  pub min_deposit: u64,
      }

impl InitializeTuktukConfigV0InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `InitializeTuktukConfigV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` approver
          ///   2. `[]` authority
                ///   3. `[writable]` tuktuk_config
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct InitializeTuktukConfigV0Builder {
            payer: Option<solana_address::Address>,
                approver: Option<solana_address::Address>,
                authority: Option<solana_address::Address>,
                tuktuk_config: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                        min_deposit: Option<u64>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializeTuktukConfigV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            #[inline(always)]
    pub fn approver(&mut self, approver: solana_address::Address) -> &mut Self {
                        self.approver = Some(approver);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn tuktuk_config(&mut self, tuktuk_config: solana_address::Address) -> &mut Self {
                        self.tuktuk_config = Some(tuktuk_config);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn min_deposit(&mut self, min_deposit: u64) -> &mut Self {
        self.min_deposit = Some(min_deposit);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = InitializeTuktukConfigV0 {
                              payer: self.payer.expect("payer is not set"),
                                        approver: self.approver.expect("approver is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        tuktuk_config: self.tuktuk_config.expect("tuktuk_config is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                      };
          let args = InitializeTuktukConfigV0InstructionArgs {
                                                              min_deposit: self.min_deposit.clone().expect("min_deposit is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `initialize_tuktuk_config_v0` CPI accounts.
  pub struct InitializeTuktukConfigV0CpiAccounts<'a, 'b> {
          
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub approver: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub tuktuk_config: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `initialize_tuktuk_config_v0` CPI instruction.
pub struct InitializeTuktukConfigV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub approver: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub tuktuk_config: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: InitializeTuktukConfigV0InstructionArgs,
  }

impl<'a, 'b> InitializeTuktukConfigV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: InitializeTuktukConfigV0CpiAccounts<'a, 'b>,
              args: InitializeTuktukConfigV0InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              payer: accounts.payer,
              approver: accounts.approver,
              authority: accounts.authority,
              tuktuk_config: accounts.tuktuk_config,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.approver.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.tuktuk_config.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = InitializeTuktukConfigV0InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.payer.clone());
                        account_infos.push(self.approver.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.tuktuk_config.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitializeTuktukConfigV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` approver
          ///   2. `[]` authority
                ///   3. `[writable]` tuktuk_config
          ///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct InitializeTuktukConfigV0CpiBuilder<'a, 'b> {
  instruction: Box<InitializeTuktukConfigV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeTuktukConfigV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitializeTuktukConfigV0CpiBuilderInstruction {
      __program: program,
              payer: None,
              approver: None,
              authority: None,
              tuktuk_config: None,
              system_program: None,
                                            min_deposit: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      #[inline(always)]
    pub fn approver(&mut self, approver: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.approver = Some(approver);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn tuktuk_config(&mut self, tuktuk_config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.tuktuk_config = Some(tuktuk_config);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn min_deposit(&mut self, min_deposit: u64) -> &mut Self {
        self.instruction.min_deposit = Some(min_deposit);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = InitializeTuktukConfigV0InstructionArgs {
                                                              min_deposit: self.instruction.min_deposit.clone().expect("min_deposit is not set"),
                                    };
        let instruction = InitializeTuktukConfigV0Cpi {
        __program: self.instruction.__program,
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          approver: self.instruction.approver.expect("approver is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          tuktuk_config: self.instruction.tuktuk_config.expect("tuktuk_config is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitializeTuktukConfigV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                approver: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                tuktuk_config: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        min_deposit: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

