//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

  pub(crate) mod r#add_queue_authority_v0;
  pub(crate) mod r#close_task_queue_v0;
  pub(crate) mod r#dequeue_task_v0;
  pub(crate) mod r#dummy_ix;
  pub(crate) mod r#initialize_task_queue_v0;
  pub(crate) mod r#initialize_tuktuk_config_v0;
  pub(crate) mod r#queue_task_v0;
  pub(crate) mod r#remove_queue_authority_v0;
  pub(crate) mod r#return_tasks_v0;
  pub(crate) mod r#run_task_v0;
  pub(crate) mod r#update_task_queue_v0;

  pub use self::r#add_queue_authority_v0::*;
  pub use self::r#close_task_queue_v0::*;
  pub use self::r#dequeue_task_v0::*;
  pub use self::r#dummy_ix::*;
  pub use self::r#initialize_task_queue_v0::*;
  pub use self::r#initialize_tuktuk_config_v0::*;
  pub use self::r#queue_task_v0::*;
  pub use self::r#remove_queue_authority_v0::*;
  pub use self::r#return_tasks_v0::*;
  pub use self::r#run_task_v0::*;
  pub use self::r#update_task_queue_v0::*;

