//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::tuktuk_client::types::TriggerV0;
use crate::tuktuk_client::types::TransactionSourceV0;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const QUEUE_TASK_V0_DISCRIMINATOR: [u8; 8] = [177, 95, 195, 252, 241, 2, 178, 88];

/// Accounts.
#[derive(Debug)]
pub struct QueueTaskV0 {
      
              
          pub payer: solana_address::Address,
          
              
          pub queue_authority: solana_address::Address,
          
              
          pub task_queue_authority: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
          
              
          pub task: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
      }

impl QueueTaskV0 {
  pub fn instruction(&self, args: QueueTaskV0InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: QueueTaskV0InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.queue_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.task_queue_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = QueueTaskV0InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct QueueTaskV0InstructionData {
            discriminator: [u8; 8],
                                          }

impl QueueTaskV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [177, 95, 195, 252, 241, 2, 178, 88],
                                                                                                      }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for QueueTaskV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct QueueTaskV0InstructionArgs {
                  pub id: u16,
                pub trigger: TriggerV0,
                pub transaction: TransactionSourceV0,
                pub crank_reward: Option<u64>,
                pub free_tasks: u8,
                pub description: String,
      }

impl QueueTaskV0InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `QueueTaskV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` queue_authority
          ///   2. `[]` task_queue_authority
                ///   3. `[writable]` task_queue
                ///   4. `[writable]` task
                ///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct QueueTaskV0Builder {
            payer: Option<solana_address::Address>,
                queue_authority: Option<solana_address::Address>,
                task_queue_authority: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                task: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                        id: Option<u16>,
                trigger: Option<TriggerV0>,
                transaction: Option<TransactionSourceV0>,
                crank_reward: Option<u64>,
                free_tasks: Option<u8>,
                description: Option<String>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl QueueTaskV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: solana_address::Address) -> &mut Self {
                        self.queue_authority = Some(queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: solana_address::Address) -> &mut Self {
                        self.task_queue_authority = Some(task_queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            #[inline(always)]
    pub fn task(&mut self, task: solana_address::Address) -> &mut Self {
                        self.task = Some(task);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn id(&mut self, id: u16) -> &mut Self {
        self.id = Some(id);
        self
      }
                #[inline(always)]
      pub fn trigger(&mut self, trigger: TriggerV0) -> &mut Self {
        self.trigger = Some(trigger);
        self
      }
                #[inline(always)]
      pub fn transaction(&mut self, transaction: TransactionSourceV0) -> &mut Self {
        self.transaction = Some(transaction);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn crank_reward(&mut self, crank_reward: u64) -> &mut Self {
        self.crank_reward = Some(crank_reward);
        self
      }
                #[inline(always)]
      pub fn free_tasks(&mut self, free_tasks: u8) -> &mut Self {
        self.free_tasks = Some(free_tasks);
        self
      }
                #[inline(always)]
      pub fn description(&mut self, description: String) -> &mut Self {
        self.description = Some(description);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = QueueTaskV0 {
                              payer: self.payer.expect("payer is not set"),
                                        queue_authority: self.queue_authority.expect("queue_authority is not set"),
                                        task_queue_authority: self.task_queue_authority.expect("task_queue_authority is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                                        task: self.task.expect("task is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                      };
          let args = QueueTaskV0InstructionArgs {
                                                              id: self.id.clone().expect("id is not set"),
                                                                  trigger: self.trigger.clone().expect("trigger is not set"),
                                                                  transaction: self.transaction.clone().expect("transaction is not set"),
                                                                  crank_reward: self.crank_reward.clone(),
                                                                  free_tasks: self.free_tasks.clone().expect("free_tasks is not set"),
                                                                  description: self.description.clone().expect("description is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `queue_task_v0` CPI accounts.
  pub struct QueueTaskV0CpiAccounts<'a, 'b> {
          
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `queue_task_v0` CPI instruction.
pub struct QueueTaskV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: QueueTaskV0InstructionArgs,
  }

impl<'a, 'b> QueueTaskV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: QueueTaskV0CpiAccounts<'a, 'b>,
              args: QueueTaskV0InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              payer: accounts.payer,
              queue_authority: accounts.queue_authority,
              task_queue_authority: accounts.task_queue_authority,
              task_queue: accounts.task_queue,
              task: accounts.task,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.queue_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.task_queue_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = QueueTaskV0InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.payer.clone());
                        account_infos.push(self.queue_authority.clone());
                        account_infos.push(self.task_queue_authority.clone());
                        account_infos.push(self.task_queue.clone());
                        account_infos.push(self.task.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `QueueTaskV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` queue_authority
          ///   2. `[]` task_queue_authority
                ///   3. `[writable]` task_queue
                ///   4. `[writable]` task
          ///   5. `[]` system_program
#[derive(Clone, Debug)]
pub struct QueueTaskV0CpiBuilder<'a, 'b> {
  instruction: Box<QueueTaskV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> QueueTaskV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(QueueTaskV0CpiBuilderInstruction {
      __program: program,
              payer: None,
              queue_authority: None,
              task_queue_authority: None,
              task_queue: None,
              task: None,
              system_program: None,
                                            id: None,
                                trigger: None,
                                transaction: None,
                                crank_reward: None,
                                free_tasks: None,
                                description: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.queue_authority = Some(queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue_authority = Some(task_queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
      #[inline(always)]
    pub fn task(&mut self, task: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task = Some(task);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn id(&mut self, id: u16) -> &mut Self {
        self.instruction.id = Some(id);
        self
      }
                #[inline(always)]
      pub fn trigger(&mut self, trigger: TriggerV0) -> &mut Self {
        self.instruction.trigger = Some(trigger);
        self
      }
                #[inline(always)]
      pub fn transaction(&mut self, transaction: TransactionSourceV0) -> &mut Self {
        self.instruction.transaction = Some(transaction);
        self
      }
                /// `[optional argument]`
#[inline(always)]
      pub fn crank_reward(&mut self, crank_reward: u64) -> &mut Self {
        self.instruction.crank_reward = Some(crank_reward);
        self
      }
                #[inline(always)]
      pub fn free_tasks(&mut self, free_tasks: u8) -> &mut Self {
        self.instruction.free_tasks = Some(free_tasks);
        self
      }
                #[inline(always)]
      pub fn description(&mut self, description: String) -> &mut Self {
        self.instruction.description = Some(description);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = QueueTaskV0InstructionArgs {
                                                              id: self.instruction.id.clone().expect("id is not set"),
                                                                  trigger: self.instruction.trigger.clone().expect("trigger is not set"),
                                                                  transaction: self.instruction.transaction.clone().expect("transaction is not set"),
                                                                  crank_reward: self.instruction.crank_reward.clone(),
                                                                  free_tasks: self.instruction.free_tasks.clone().expect("free_tasks is not set"),
                                                                  description: self.instruction.description.clone().expect("description is not set"),
                                    };
        let instruction = QueueTaskV0Cpi {
        __program: self.instruction.__program,
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          queue_authority: self.instruction.queue_authority.expect("queue_authority is not set"),
                  
          task_queue_authority: self.instruction.task_queue_authority.expect("task_queue_authority is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                  
          task: self.instruction.task.expect("task is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct QueueTaskV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                task: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        id: Option<u16>,
                trigger: Option<TriggerV0>,
                transaction: Option<TransactionSourceV0>,
                crank_reward: Option<u64>,
                free_tasks: Option<u8>,
                description: Option<String>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

