//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const REMOVE_QUEUE_AUTHORITY_V0_DISCRIMINATOR: [u8; 8] = [180, 26, 196, 229, 80, 40, 245, 187];

/// Accounts.
#[derive(Debug)]
pub struct RemoveQueueAuthorityV0 {
      
              
          pub payer: solana_address::Address,
          
              
          pub rent_refund: solana_address::Address,
          
              
          pub update_authority: solana_address::Address,
          
              
          pub queue_authority: solana_address::Address,
          
              
          pub task_queue_authority: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
      }

impl RemoveQueueAuthorityV0 {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.update_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.queue_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = RemoveQueueAuthorityV0InstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct RemoveQueueAuthorityV0InstructionData {
            discriminator: [u8; 8],
      }

impl RemoveQueueAuthorityV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [180, 26, 196, 229, 80, 40, 245, 187],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for RemoveQueueAuthorityV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `RemoveQueueAuthorityV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[writable]` rent_refund
                ///   2. `[signer]` update_authority
          ///   3. `[]` queue_authority
                ///   4. `[writable]` task_queue_authority
                ///   5. `[writable]` task_queue
#[derive(Clone, Debug, Default)]
pub struct RemoveQueueAuthorityV0Builder {
            payer: Option<solana_address::Address>,
                rent_refund: Option<solana_address::Address>,
                update_authority: Option<solana_address::Address>,
                queue_authority: Option<solana_address::Address>,
                task_queue_authority: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RemoveQueueAuthorityV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn update_authority(&mut self, update_authority: solana_address::Address) -> &mut Self {
                        self.update_authority = Some(update_authority);
                    self
    }
            #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: solana_address::Address) -> &mut Self {
                        self.queue_authority = Some(queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: solana_address::Address) -> &mut Self {
                        self.task_queue_authority = Some(task_queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = RemoveQueueAuthorityV0 {
                              payer: self.payer.expect("payer is not set"),
                                        rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        update_authority: self.update_authority.expect("update_authority is not set"),
                                        queue_authority: self.queue_authority.expect("queue_authority is not set"),
                                        task_queue_authority: self.task_queue_authority.expect("task_queue_authority is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `remove_queue_authority_v0` CPI accounts.
  pub struct RemoveQueueAuthorityV0CpiAccounts<'a, 'b> {
          
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub update_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
            }

/// `remove_queue_authority_v0` CPI instruction.
pub struct RemoveQueueAuthorityV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub update_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> RemoveQueueAuthorityV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: RemoveQueueAuthorityV0CpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              payer: accounts.payer,
              rent_refund: accounts.rent_refund,
              update_authority: accounts.update_authority,
              queue_authority: accounts.queue_authority,
              task_queue_authority: accounts.task_queue_authority,
              task_queue: accounts.task_queue,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.update_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.queue_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = RemoveQueueAuthorityV0InstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.payer.clone());
                        account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.update_authority.clone());
                        account_infos.push(self.queue_authority.clone());
                        account_infos.push(self.task_queue_authority.clone());
                        account_infos.push(self.task_queue.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `RemoveQueueAuthorityV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[writable]` rent_refund
                ///   2. `[signer]` update_authority
          ///   3. `[]` queue_authority
                ///   4. `[writable]` task_queue_authority
                ///   5. `[writable]` task_queue
#[derive(Clone, Debug)]
pub struct RemoveQueueAuthorityV0CpiBuilder<'a, 'b> {
  instruction: Box<RemoveQueueAuthorityV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RemoveQueueAuthorityV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(RemoveQueueAuthorityV0CpiBuilderInstruction {
      __program: program,
              payer: None,
              rent_refund: None,
              update_authority: None,
              queue_authority: None,
              task_queue_authority: None,
              task_queue: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn update_authority(&mut self, update_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.update_authority = Some(update_authority);
                    self
    }
      #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.queue_authority = Some(queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue_authority = Some(task_queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = RemoveQueueAuthorityV0Cpi {
        __program: self.instruction.__program,
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          update_authority: self.instruction.update_authority.expect("update_authority is not set"),
                  
          queue_authority: self.instruction.queue_authority.expect("queue_authority is not set"),
                  
          task_queue_authority: self.instruction.task_queue_authority.expect("task_queue_authority is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct RemoveQueueAuthorityV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                update_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

