//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const RUN_TASK_V0_DISCRIMINATOR: [u8; 8] = [52, 184, 39, 129, 126, 245, 176, 237];

/// Accounts.
#[derive(Debug)]
pub struct RunTaskV0 {
      
              
          pub crank_turner: solana_address::Address,
          
              
          pub rent_refund: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
          
              
          pub task: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
                /// the supplied Sysvar could be anything else.
/// The Instruction Sysvar has not been implemented
/// in the Anchor framework yet, so this is the safe approach.

    
              
          pub sysvar_instructions: solana_address::Address,
      }

impl RunTaskV0 {
  pub fn instruction(&self, args: RunTaskV0InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: RunTaskV0InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.crank_turner,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.sysvar_instructions,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = RunTaskV0InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct RunTaskV0InstructionData {
            discriminator: [u8; 8],
            }

impl RunTaskV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [52, 184, 39, 129, 126, 245, 176, 237],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for RunTaskV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct RunTaskV0InstructionArgs {
                  pub free_task_ids: Vec<u16>,
      }

impl RunTaskV0InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `RunTaskV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` crank_turner
                ///   1. `[writable]` rent_refund
                ///   2. `[writable]` task_queue
                ///   3. `[writable]` task
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   5. `[optional]` sysvar_instructions (default to `Sysvar1nstructions1111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct RunTaskV0Builder {
            crank_turner: Option<solana_address::Address>,
                rent_refund: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                task: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                sysvar_instructions: Option<solana_address::Address>,
                        free_task_ids: Option<Vec<u16>>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RunTaskV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn crank_turner(&mut self, crank_turner: solana_address::Address) -> &mut Self {
                        self.crank_turner = Some(crank_turner);
                    self
    }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            #[inline(always)]
    pub fn task(&mut self, task: solana_address::Address) -> &mut Self {
                        self.task = Some(task);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account, default to 'Sysvar1nstructions1111111111111111111111111']`
/// the supplied Sysvar could be anything else.
/// The Instruction Sysvar has not been implemented
/// in the Anchor framework yet, so this is the safe approach.
#[inline(always)]
    pub fn sysvar_instructions(&mut self, sysvar_instructions: solana_address::Address) -> &mut Self {
                        self.sysvar_instructions = Some(sysvar_instructions);
                    self
    }
                    #[inline(always)]
      pub fn free_task_ids(&mut self, free_task_ids: Vec<u16>) -> &mut Self {
        self.free_task_ids = Some(free_task_ids);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = RunTaskV0 {
                              crank_turner: self.crank_turner.expect("crank_turner is not set"),
                                        rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                                        task: self.task.expect("task is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                                        sysvar_instructions: self.sysvar_instructions.unwrap_or(solana_address::address!("Sysvar1nstructions1111111111111111111111111")),
                      };
          let args = RunTaskV0InstructionArgs {
                                                              free_task_ids: self.free_task_ids.clone().expect("free_task_ids is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `run_task_v0` CPI accounts.
  pub struct RunTaskV0CpiAccounts<'a, 'b> {
          
                    
              pub crank_turner: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                        /// the supplied Sysvar could be anything else.
/// The Instruction Sysvar has not been implemented
/// in the Anchor framework yet, so this is the safe approach.

      
                    
              pub sysvar_instructions: &'b solana_account_info::AccountInfo<'a>,
            }

/// `run_task_v0` CPI instruction.
pub struct RunTaskV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub crank_turner: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
                /// the supplied Sysvar could be anything else.
/// The Instruction Sysvar has not been implemented
/// in the Anchor framework yet, so this is the safe approach.

    
              
          pub sysvar_instructions: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: RunTaskV0InstructionArgs,
  }

impl<'a, 'b> RunTaskV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: RunTaskV0CpiAccounts<'a, 'b>,
              args: RunTaskV0InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              crank_turner: accounts.crank_turner,
              rent_refund: accounts.rent_refund,
              task_queue: accounts.task_queue,
              task: accounts.task,
              system_program: accounts.system_program,
              sysvar_instructions: accounts.sysvar_instructions,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(6+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.crank_turner.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.sysvar_instructions.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = RunTaskV0InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::tuktuk_client::TUKTUK_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(7 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.crank_turner.clone());
                        account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.task_queue.clone());
                        account_infos.push(self.task.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.sysvar_instructions.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `RunTaskV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` crank_turner
                ///   1. `[writable]` rent_refund
                ///   2. `[writable]` task_queue
                ///   3. `[writable]` task
          ///   4. `[]` system_program
          ///   5. `[]` sysvar_instructions
#[derive(Clone, Debug)]
pub struct RunTaskV0CpiBuilder<'a, 'b> {
  instruction: Box<RunTaskV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RunTaskV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(RunTaskV0CpiBuilderInstruction {
      __program: program,
              crank_turner: None,
              rent_refund: None,
              task_queue: None,
              task: None,
              system_program: None,
              sysvar_instructions: None,
                                            free_task_ids: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn crank_turner(&mut self, crank_turner: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.crank_turner = Some(crank_turner);
                    self
    }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
      #[inline(always)]
    pub fn task(&mut self, task: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task = Some(task);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      /// the supplied Sysvar could be anything else.
/// The Instruction Sysvar has not been implemented
/// in the Anchor framework yet, so this is the safe approach.
#[inline(always)]
    pub fn sysvar_instructions(&mut self, sysvar_instructions: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.sysvar_instructions = Some(sysvar_instructions);
                    self
    }
                    #[inline(always)]
      pub fn free_task_ids(&mut self, free_task_ids: Vec<u16>) -> &mut Self {
        self.instruction.free_task_ids = Some(free_task_ids);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = RunTaskV0InstructionArgs {
                                                              free_task_ids: self.instruction.free_task_ids.clone().expect("free_task_ids is not set"),
                                    };
        let instruction = RunTaskV0Cpi {
        __program: self.instruction.__program,
                  
          crank_turner: self.instruction.crank_turner.expect("crank_turner is not set"),
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                  
          task: self.instruction.task.expect("task is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          sysvar_instructions: self.instruction.sysvar_instructions.expect("sysvar_instructions is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct RunTaskV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            crank_turner: Option<&'b solana_account_info::AccountInfo<'a>>,
                rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                task: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                sysvar_instructions: Option<&'b solana_account_info::AccountInfo<'a>>,
                        free_task_ids: Option<Vec<u16>>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

