//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

      pub mod accounts;
        // See note in cron_client/mod.rs — codama error enum suppressed.
        // pub mod errors;
        pub mod instructions;
        pub mod programs;
        pub mod shared;
        pub mod types;
  
  pub(crate) use programs::*;
