//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::{address, Address};


  /// `tuktuk` program ID.
  pub const TUKTUK_ID: Address = address!("tuktukUrfhXT6ZT77QTU8RQtvgL967uRuVagWF57zVA");

