//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const CLOSE_CRON_JOB_V0_DISCRIMINATOR: [u8; 8] = [114, 152, 214, 24, 97, 36, 231, 102];

/// Accounts.
#[derive(Debug)]
pub struct CloseCronJobV0 {
      
              
          pub rent_refund: solana_address::Address,
          
              
          pub authority: solana_address::Address,
          
              
          pub user_cron_jobs: solana_address::Address,
          
              
          pub cron_job: solana_address::Address,
          
              
          pub cron_job_name_mapping: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
          
              
          pub task_return_account1: solana_address::Address,
          
              
          pub task_return_account2: solana_address::Address,
      }

impl CloseCronJobV0 {
  pub fn instruction(&self) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(&[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_cron_jobs,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job_name_mapping,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_return_account1,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_return_account2,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let data = CloseCronJobV0InstructionData::new().try_to_vec().unwrap();
    
    solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct CloseCronJobV0InstructionData {
            discriminator: [u8; 8],
      }

impl CloseCronJobV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [114, 152, 214, 24, 97, 36, 231, 102],
                  }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for CloseCronJobV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}



/// Instruction builder for `CloseCronJobV0`.
///
/// ### Accounts:
///
                ///   0. `[writable]` rent_refund
                ///   1. `[signer]` authority
                ///   2. `[writable]` user_cron_jobs
                ///   3. `[writable]` cron_job
                ///   4. `[writable]` cron_job_name_mapping
                ///   5. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   6. `[writable]` task_return_account1
                ///   7. `[writable]` task_return_account2
#[derive(Clone, Debug, Default)]
pub struct CloseCronJobV0Builder {
            rent_refund: Option<solana_address::Address>,
                authority: Option<solana_address::Address>,
                user_cron_jobs: Option<solana_address::Address>,
                cron_job: Option<solana_address::Address>,
                cron_job_name_mapping: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                task_return_account1: Option<solana_address::Address>,
                task_return_account2: Option<solana_address::Address>,
                __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CloseCronJobV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn user_cron_jobs(&mut self, user_cron_jobs: solana_address::Address) -> &mut Self {
                        self.user_cron_jobs = Some(user_cron_jobs);
                    self
    }
            #[inline(always)]
    pub fn cron_job(&mut self, cron_job: solana_address::Address) -> &mut Self {
                        self.cron_job = Some(cron_job);
                    self
    }
            #[inline(always)]
    pub fn cron_job_name_mapping(&mut self, cron_job_name_mapping: solana_address::Address) -> &mut Self {
                        self.cron_job_name_mapping = Some(cron_job_name_mapping);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            #[inline(always)]
    pub fn task_return_account1(&mut self, task_return_account1: solana_address::Address) -> &mut Self {
                        self.task_return_account1 = Some(task_return_account1);
                    self
    }
            #[inline(always)]
    pub fn task_return_account2(&mut self, task_return_account2: solana_address::Address) -> &mut Self {
                        self.task_return_account2 = Some(task_return_account2);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = CloseCronJobV0 {
                              rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        user_cron_jobs: self.user_cron_jobs.expect("user_cron_jobs is not set"),
                                        cron_job: self.cron_job.expect("cron_job is not set"),
                                        cron_job_name_mapping: self.cron_job_name_mapping.expect("cron_job_name_mapping is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                                        task_return_account1: self.task_return_account1.expect("task_return_account1 is not set"),
                                        task_return_account2: self.task_return_account2.expect("task_return_account2 is not set"),
                      };
    
    accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
  }
}

  /// `close_cron_job_v0` CPI accounts.
  pub struct CloseCronJobV0CpiAccounts<'a, 'b> {
          
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_cron_jobs: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_return_account1: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_return_account2: &'b solana_account_info::AccountInfo<'a>,
            }

/// `close_cron_job_v0` CPI instruction.
pub struct CloseCronJobV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_cron_jobs: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_return_account1: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_return_account2: &'b solana_account_info::AccountInfo<'a>,
        }

impl<'a, 'b> CloseCronJobV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: CloseCronJobV0CpiAccounts<'a, 'b>,
          ) -> Self {
    Self {
      __program: program,
              rent_refund: accounts.rent_refund,
              authority: accounts.authority,
              user_cron_jobs: accounts.user_cron_jobs,
              cron_job: accounts.cron_job,
              cron_job_name_mapping: accounts.cron_job_name_mapping,
              system_program: accounts.system_program,
              task_return_account1: accounts.task_return_account1,
              task_return_account2: accounts.task_return_account2,
                }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(8+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_cron_jobs.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job_name_mapping.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_return_account1.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_return_account2.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let data = CloseCronJobV0InstructionData::new().try_to_vec().unwrap();
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(9 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.user_cron_jobs.clone());
                        account_infos.push(self.cron_job.clone());
                        account_infos.push(self.cron_job_name_mapping.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.task_return_account1.clone());
                        account_infos.push(self.task_return_account2.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `CloseCronJobV0` via CPI.
///
/// ### Accounts:
///
                ///   0. `[writable]` rent_refund
                ///   1. `[signer]` authority
                ///   2. `[writable]` user_cron_jobs
                ///   3. `[writable]` cron_job
                ///   4. `[writable]` cron_job_name_mapping
          ///   5. `[]` system_program
                ///   6. `[writable]` task_return_account1
                ///   7. `[writable]` task_return_account2
#[derive(Clone, Debug)]
pub struct CloseCronJobV0CpiBuilder<'a, 'b> {
  instruction: Box<CloseCronJobV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CloseCronJobV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(CloseCronJobV0CpiBuilderInstruction {
      __program: program,
              rent_refund: None,
              authority: None,
              user_cron_jobs: None,
              cron_job: None,
              cron_job_name_mapping: None,
              system_program: None,
              task_return_account1: None,
              task_return_account2: None,
                                __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn user_cron_jobs(&mut self, user_cron_jobs: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_cron_jobs = Some(user_cron_jobs);
                    self
    }
      #[inline(always)]
    pub fn cron_job(&mut self, cron_job: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job = Some(cron_job);
                    self
    }
      #[inline(always)]
    pub fn cron_job_name_mapping(&mut self, cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job_name_mapping = Some(cron_job_name_mapping);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn task_return_account1(&mut self, task_return_account1: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_return_account1 = Some(task_return_account1);
                    self
    }
      #[inline(always)]
    pub fn task_return_account2(&mut self, task_return_account2: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_return_account2 = Some(task_return_account2);
                    self
    }
            /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = CloseCronJobV0Cpi {
        __program: self.instruction.__program,
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          user_cron_jobs: self.instruction.user_cron_jobs.expect("user_cron_jobs is not set"),
                  
          cron_job: self.instruction.cron_job.expect("cron_job is not set"),
                  
          cron_job_name_mapping: self.instruction.cron_job_name_mapping.expect("cron_job_name_mapping is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          task_return_account1: self.instruction.task_return_account1.expect("task_return_account1 is not set"),
                  
          task_return_account2: self.instruction.task_return_account2.expect("task_return_account2 is not set"),
                    };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct CloseCronJobV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_cron_jobs: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job_name_mapping: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_return_account1: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_return_account2: Option<&'b solana_account_info::AccountInfo<'a>>,
                /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

