//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const INITIALIZE_CRON_JOB_V0_DISCRIMINATOR: [u8; 8] = [246, 64, 133, 115, 169, 84, 130, 133];

/// Accounts.
#[derive(Debug)]
pub struct InitializeCronJobV0 {
      
              
          pub payer: solana_address::Address,
          
              
          pub queue_authority: solana_address::Address,
          
              
          pub task_queue_authority: solana_address::Address,
          
              
          pub authority: solana_address::Address,
          
              
          pub user_cron_jobs: solana_address::Address,
          
              
          pub cron_job: solana_address::Address,
          
              
          pub cron_job_name_mapping: solana_address::Address,
          
              
          pub task_queue: solana_address::Address,
          
              
          pub task: solana_address::Address,
          
              
          pub task_return_account1: solana_address::Address,
          
              
          pub task_return_account2: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
          
              
          pub tuktuk_program: solana_address::Address,
      }

impl InitializeCronJobV0 {
  pub fn instruction(&self, args: InitializeCronJobV0InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: InitializeCronJobV0InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(13+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.payer,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.queue_authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.task_queue_authority,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.user_cron_jobs,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job_name_mapping,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_queue,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_return_account1,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.task_return_account2,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.tuktuk_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = InitializeCronJobV0InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct InitializeCronJobV0InstructionData {
            discriminator: [u8; 8],
                              }

impl InitializeCronJobV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [246, 64, 133, 115, 169, 84, 130, 133],
                                                                          }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for InitializeCronJobV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct InitializeCronJobV0InstructionArgs {
                  pub schedule: String,
                pub name: String,
                pub free_tasks_per_transaction: u8,
                pub num_tasks_per_queue_call: u8,
      }

impl InitializeCronJobV0InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `InitializeCronJobV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` queue_authority
          ///   2. `[]` task_queue_authority
                ///   3. `[signer]` authority
                ///   4. `[writable]` user_cron_jobs
                ///   5. `[writable]` cron_job
                ///   6. `[writable]` cron_job_name_mapping
                ///   7. `[writable]` task_queue
                ///   8. `[writable]` task
                ///   9. `[writable]` task_return_account1
                ///   10. `[writable]` task_return_account2
                ///   11. `[optional]` system_program (default to `11111111111111111111111111111111`)
                ///   12. `[optional]` tuktuk_program (default to `tuktukUrfhXT6ZT77QTU8RQtvgL967uRuVagWF57zVA`)
#[derive(Clone, Debug, Default)]
pub struct InitializeCronJobV0Builder {
            payer: Option<solana_address::Address>,
                queue_authority: Option<solana_address::Address>,
                task_queue_authority: Option<solana_address::Address>,
                authority: Option<solana_address::Address>,
                user_cron_jobs: Option<solana_address::Address>,
                cron_job: Option<solana_address::Address>,
                cron_job_name_mapping: Option<solana_address::Address>,
                task_queue: Option<solana_address::Address>,
                task: Option<solana_address::Address>,
                task_return_account1: Option<solana_address::Address>,
                task_return_account2: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                tuktuk_program: Option<solana_address::Address>,
                        schedule: Option<String>,
                name: Option<String>,
                free_tasks_per_transaction: Option<u8>,
                num_tasks_per_queue_call: Option<u8>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl InitializeCronJobV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn payer(&mut self, payer: solana_address::Address) -> &mut Self {
                        self.payer = Some(payer);
                    self
    }
            #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: solana_address::Address) -> &mut Self {
                        self.queue_authority = Some(queue_authority);
                    self
    }
            #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: solana_address::Address) -> &mut Self {
                        self.task_queue_authority = Some(task_queue_authority);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn user_cron_jobs(&mut self, user_cron_jobs: solana_address::Address) -> &mut Self {
                        self.user_cron_jobs = Some(user_cron_jobs);
                    self
    }
            #[inline(always)]
    pub fn cron_job(&mut self, cron_job: solana_address::Address) -> &mut Self {
                        self.cron_job = Some(cron_job);
                    self
    }
            #[inline(always)]
    pub fn cron_job_name_mapping(&mut self, cron_job_name_mapping: solana_address::Address) -> &mut Self {
                        self.cron_job_name_mapping = Some(cron_job_name_mapping);
                    self
    }
            #[inline(always)]
    pub fn task_queue(&mut self, task_queue: solana_address::Address) -> &mut Self {
                        self.task_queue = Some(task_queue);
                    self
    }
            #[inline(always)]
    pub fn task(&mut self, task: solana_address::Address) -> &mut Self {
                        self.task = Some(task);
                    self
    }
            #[inline(always)]
    pub fn task_return_account1(&mut self, task_return_account1: solana_address::Address) -> &mut Self {
                        self.task_return_account1 = Some(task_return_account1);
                    self
    }
            #[inline(always)]
    pub fn task_return_account2(&mut self, task_return_account2: solana_address::Address) -> &mut Self {
                        self.task_return_account2 = Some(task_return_account2);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
            /// `[optional account, default to 'tuktukUrfhXT6ZT77QTU8RQtvgL967uRuVagWF57zVA']`
#[inline(always)]
    pub fn tuktuk_program(&mut self, tuktuk_program: solana_address::Address) -> &mut Self {
                        self.tuktuk_program = Some(tuktuk_program);
                    self
    }
                    #[inline(always)]
      pub fn schedule(&mut self, schedule: String) -> &mut Self {
        self.schedule = Some(schedule);
        self
      }
                #[inline(always)]
      pub fn name(&mut self, name: String) -> &mut Self {
        self.name = Some(name);
        self
      }
                #[inline(always)]
      pub fn free_tasks_per_transaction(&mut self, free_tasks_per_transaction: u8) -> &mut Self {
        self.free_tasks_per_transaction = Some(free_tasks_per_transaction);
        self
      }
                #[inline(always)]
      pub fn num_tasks_per_queue_call(&mut self, num_tasks_per_queue_call: u8) -> &mut Self {
        self.num_tasks_per_queue_call = Some(num_tasks_per_queue_call);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = InitializeCronJobV0 {
                              payer: self.payer.expect("payer is not set"),
                                        queue_authority: self.queue_authority.expect("queue_authority is not set"),
                                        task_queue_authority: self.task_queue_authority.expect("task_queue_authority is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        user_cron_jobs: self.user_cron_jobs.expect("user_cron_jobs is not set"),
                                        cron_job: self.cron_job.expect("cron_job is not set"),
                                        cron_job_name_mapping: self.cron_job_name_mapping.expect("cron_job_name_mapping is not set"),
                                        task_queue: self.task_queue.expect("task_queue is not set"),
                                        task: self.task.expect("task is not set"),
                                        task_return_account1: self.task_return_account1.expect("task_return_account1 is not set"),
                                        task_return_account2: self.task_return_account2.expect("task_return_account2 is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                                        tuktuk_program: self.tuktuk_program.unwrap_or(solana_address::address!("tuktukUrfhXT6ZT77QTU8RQtvgL967uRuVagWF57zVA")),
                      };
          let args = InitializeCronJobV0InstructionArgs {
                                                              schedule: self.schedule.clone().expect("schedule is not set"),
                                                                  name: self.name.clone().expect("name is not set"),
                                                                  free_tasks_per_transaction: self.free_tasks_per_transaction.clone().expect("free_tasks_per_transaction is not set"),
                                                                  num_tasks_per_queue_call: self.num_tasks_per_queue_call.clone().expect("num_tasks_per_queue_call is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `initialize_cron_job_v0` CPI accounts.
  pub struct InitializeCronJobV0CpiAccounts<'a, 'b> {
          
                    
              pub payer: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub user_cron_jobs: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_queue: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_return_account1: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub task_return_account2: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub tuktuk_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `initialize_cron_job_v0` CPI instruction.
pub struct InitializeCronJobV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub payer: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue_authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub user_cron_jobs: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_queue: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_return_account1: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub task_return_account2: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub tuktuk_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: InitializeCronJobV0InstructionArgs,
  }

impl<'a, 'b> InitializeCronJobV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: InitializeCronJobV0CpiAccounts<'a, 'b>,
              args: InitializeCronJobV0InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              payer: accounts.payer,
              queue_authority: accounts.queue_authority,
              task_queue_authority: accounts.task_queue_authority,
              authority: accounts.authority,
              user_cron_jobs: accounts.user_cron_jobs,
              cron_job: accounts.cron_job,
              cron_job_name_mapping: accounts.cron_job_name_mapping,
              task_queue: accounts.task_queue,
              task: accounts.task,
              task_return_account1: accounts.task_return_account1,
              task_return_account2: accounts.task_return_account2,
              system_program: accounts.system_program,
              tuktuk_program: accounts.tuktuk_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(13+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.payer.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.queue_authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.task_queue_authority.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.user_cron_jobs.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job_name_mapping.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_queue.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_return_account1.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.task_return_account2.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.tuktuk_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = InitializeCronJobV0InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(14 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.payer.clone());
                        account_infos.push(self.queue_authority.clone());
                        account_infos.push(self.task_queue_authority.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.user_cron_jobs.clone());
                        account_infos.push(self.cron_job.clone());
                        account_infos.push(self.cron_job_name_mapping.clone());
                        account_infos.push(self.task_queue.clone());
                        account_infos.push(self.task.clone());
                        account_infos.push(self.task_return_account1.clone());
                        account_infos.push(self.task_return_account2.clone());
                        account_infos.push(self.system_program.clone());
                        account_infos.push(self.tuktuk_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `InitializeCronJobV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` payer
                ///   1. `[signer]` queue_authority
          ///   2. `[]` task_queue_authority
                ///   3. `[signer]` authority
                ///   4. `[writable]` user_cron_jobs
                ///   5. `[writable]` cron_job
                ///   6. `[writable]` cron_job_name_mapping
                ///   7. `[writable]` task_queue
                ///   8. `[writable]` task
                ///   9. `[writable]` task_return_account1
                ///   10. `[writable]` task_return_account2
          ///   11. `[]` system_program
          ///   12. `[]` tuktuk_program
#[derive(Clone, Debug)]
pub struct InitializeCronJobV0CpiBuilder<'a, 'b> {
  instruction: Box<InitializeCronJobV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> InitializeCronJobV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(InitializeCronJobV0CpiBuilderInstruction {
      __program: program,
              payer: None,
              queue_authority: None,
              task_queue_authority: None,
              authority: None,
              user_cron_jobs: None,
              cron_job: None,
              cron_job_name_mapping: None,
              task_queue: None,
              task: None,
              task_return_account1: None,
              task_return_account2: None,
              system_program: None,
              tuktuk_program: None,
                                            schedule: None,
                                name: None,
                                free_tasks_per_transaction: None,
                                num_tasks_per_queue_call: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.payer = Some(payer);
                    self
    }
      #[inline(always)]
    pub fn queue_authority(&mut self, queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.queue_authority = Some(queue_authority);
                    self
    }
      #[inline(always)]
    pub fn task_queue_authority(&mut self, task_queue_authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue_authority = Some(task_queue_authority);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn user_cron_jobs(&mut self, user_cron_jobs: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_cron_jobs = Some(user_cron_jobs);
                    self
    }
      #[inline(always)]
    pub fn cron_job(&mut self, cron_job: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job = Some(cron_job);
                    self
    }
      #[inline(always)]
    pub fn cron_job_name_mapping(&mut self, cron_job_name_mapping: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job_name_mapping = Some(cron_job_name_mapping);
                    self
    }
      #[inline(always)]
    pub fn task_queue(&mut self, task_queue: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_queue = Some(task_queue);
                    self
    }
      #[inline(always)]
    pub fn task(&mut self, task: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task = Some(task);
                    self
    }
      #[inline(always)]
    pub fn task_return_account1(&mut self, task_return_account1: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_return_account1 = Some(task_return_account1);
                    self
    }
      #[inline(always)]
    pub fn task_return_account2(&mut self, task_return_account2: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.task_return_account2 = Some(task_return_account2);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
      #[inline(always)]
    pub fn tuktuk_program(&mut self, tuktuk_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.tuktuk_program = Some(tuktuk_program);
                    self
    }
                    #[inline(always)]
      pub fn schedule(&mut self, schedule: String) -> &mut Self {
        self.instruction.schedule = Some(schedule);
        self
      }
                #[inline(always)]
      pub fn name(&mut self, name: String) -> &mut Self {
        self.instruction.name = Some(name);
        self
      }
                #[inline(always)]
      pub fn free_tasks_per_transaction(&mut self, free_tasks_per_transaction: u8) -> &mut Self {
        self.instruction.free_tasks_per_transaction = Some(free_tasks_per_transaction);
        self
      }
                #[inline(always)]
      pub fn num_tasks_per_queue_call(&mut self, num_tasks_per_queue_call: u8) -> &mut Self {
        self.instruction.num_tasks_per_queue_call = Some(num_tasks_per_queue_call);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = InitializeCronJobV0InstructionArgs {
                                                              schedule: self.instruction.schedule.clone().expect("schedule is not set"),
                                                                  name: self.instruction.name.clone().expect("name is not set"),
                                                                  free_tasks_per_transaction: self.instruction.free_tasks_per_transaction.clone().expect("free_tasks_per_transaction is not set"),
                                                                  num_tasks_per_queue_call: self.instruction.num_tasks_per_queue_call.clone().expect("num_tasks_per_queue_call is not set"),
                                    };
        let instruction = InitializeCronJobV0Cpi {
        __program: self.instruction.__program,
                  
          payer: self.instruction.payer.expect("payer is not set"),
                  
          queue_authority: self.instruction.queue_authority.expect("queue_authority is not set"),
                  
          task_queue_authority: self.instruction.task_queue_authority.expect("task_queue_authority is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          user_cron_jobs: self.instruction.user_cron_jobs.expect("user_cron_jobs is not set"),
                  
          cron_job: self.instruction.cron_job.expect("cron_job is not set"),
                  
          cron_job_name_mapping: self.instruction.cron_job_name_mapping.expect("cron_job_name_mapping is not set"),
                  
          task_queue: self.instruction.task_queue.expect("task_queue is not set"),
                  
          task: self.instruction.task.expect("task is not set"),
                  
          task_return_account1: self.instruction.task_return_account1.expect("task_return_account1 is not set"),
                  
          task_return_account2: self.instruction.task_return_account2.expect("task_return_account2 is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                  
          tuktuk_program: self.instruction.tuktuk_program.expect("tuktuk_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct InitializeCronJobV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            payer: Option<&'b solana_account_info::AccountInfo<'a>>,
                queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                user_cron_jobs: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job_name_mapping: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_queue: Option<&'b solana_account_info::AccountInfo<'a>>,
                task: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_return_account1: Option<&'b solana_account_info::AccountInfo<'a>>,
                task_return_account2: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                tuktuk_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        schedule: Option<String>,
                name: Option<String>,
                free_tasks_per_transaction: Option<u8>,
                num_tasks_per_queue_call: Option<u8>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

