//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

pub const REMOVE_CRON_TRANSACTION_V0_DISCRIMINATOR: [u8; 8] = [207, 237, 8, 195, 65, 111, 124, 247];

/// Accounts.
#[derive(Debug)]
pub struct RemoveCronTransactionV0 {
      
              
          pub rent_refund: solana_address::Address,
          
              
          pub authority: solana_address::Address,
          
              
          pub cron_job: solana_address::Address,
          
              
          pub cron_job_transaction: solana_address::Address,
          
              
          pub system_program: solana_address::Address,
      }

impl RemoveCronTransactionV0 {
  pub fn instruction(&self, args: RemoveCronTransactionV0InstructionArgs) -> solana_instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: RemoveCronTransactionV0InstructionArgs, remaining_accounts: &[solana_instruction::AccountMeta]) -> solana_instruction::Instruction {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            self.rent_refund,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.authority,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            self.cron_job_transaction,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = RemoveCronTransactionV0InstructionData::new().try_to_vec().unwrap();
          let mut args = args.try_to_vec().unwrap();
      data.append(&mut args);
    
    solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct RemoveCronTransactionV0InstructionData {
            discriminator: [u8; 8],
            }

impl RemoveCronTransactionV0InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [207, 237, 8, 195, 65, 111, 124, 247],
                                }
  }

    pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
  }

impl Default for RemoveCronTransactionV0InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
 pub struct RemoveCronTransactionV0InstructionArgs {
                  pub index: u32,
      }

impl RemoveCronTransactionV0InstructionArgs {
  pub(crate) fn try_to_vec(&self) -> Result<Vec<u8>, std::io::Error> {
    borsh::to_vec(self)
  }
}


/// Instruction builder for `RemoveCronTransactionV0`.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` rent_refund
                ///   1. `[signer]` authority
                ///   2. `[writable]` cron_job
                ///   3. `[writable]` cron_job_transaction
                ///   4. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct RemoveCronTransactionV0Builder {
            rent_refund: Option<solana_address::Address>,
                authority: Option<solana_address::Address>,
                cron_job: Option<solana_address::Address>,
                cron_job_transaction: Option<solana_address::Address>,
                system_program: Option<solana_address::Address>,
                        index: Option<u32>,
        __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl RemoveCronTransactionV0Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: solana_address::Address) -> &mut Self {
                        self.rent_refund = Some(rent_refund);
                    self
    }
            #[inline(always)]
    pub fn authority(&mut self, authority: solana_address::Address) -> &mut Self {
                        self.authority = Some(authority);
                    self
    }
            #[inline(always)]
    pub fn cron_job(&mut self, cron_job: solana_address::Address) -> &mut Self {
                        self.cron_job = Some(cron_job);
                    self
    }
            #[inline(always)]
    pub fn cron_job_transaction(&mut self, cron_job_transaction: solana_address::Address) -> &mut Self {
                        self.cron_job_transaction = Some(cron_job_transaction);
                    self
    }
            /// `[optional account, default to '11111111111111111111111111111111']`
#[inline(always)]
    pub fn system_program(&mut self, system_program: solana_address::Address) -> &mut Self {
                        self.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn index(&mut self, index: u32) -> &mut Self {
        self.index = Some(index);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_instruction::Instruction {
    let accounts = RemoveCronTransactionV0 {
                              rent_refund: self.rent_refund.expect("rent_refund is not set"),
                                        authority: self.authority.expect("authority is not set"),
                                        cron_job: self.cron_job.expect("cron_job is not set"),
                                        cron_job_transaction: self.cron_job_transaction.expect("cron_job_transaction is not set"),
                                        system_program: self.system_program.unwrap_or(solana_address::address!("11111111111111111111111111111111")),
                      };
          let args = RemoveCronTransactionV0InstructionArgs {
                                                              index: self.index.clone().expect("index is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `remove_cron_transaction_v0` CPI accounts.
  pub struct RemoveCronTransactionV0CpiAccounts<'a, 'b> {
          
                    
              pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub authority: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub cron_job_transaction: &'b solana_account_info::AccountInfo<'a>,
                
                    
              pub system_program: &'b solana_account_info::AccountInfo<'a>,
            }

/// `remove_cron_transaction_v0` CPI instruction.
pub struct RemoveCronTransactionV0Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_account_info::AccountInfo<'a>,
      
              
          pub rent_refund: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub authority: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub cron_job_transaction: &'b solana_account_info::AccountInfo<'a>,
          
              
          pub system_program: &'b solana_account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: RemoveCronTransactionV0InstructionArgs,
  }

impl<'a, 'b> RemoveCronTransactionV0Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_account_info::AccountInfo<'a>,
          accounts: RemoveCronTransactionV0CpiAccounts<'a, 'b>,
              args: RemoveCronTransactionV0InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              rent_refund: accounts.rent_refund,
              authority: accounts.authority,
              cron_job: accounts.cron_job,
              cron_job_transaction: accounts.cron_job_transaction,
              system_program: accounts.system_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program_error::ProgramResult {
    let mut accounts = Vec::with_capacity(5+ remaining_accounts.len());
                            accounts.push(solana_instruction::AccountMeta::new(
            *self.rent_refund.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.authority.key,
            true
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new(
            *self.cron_job_transaction.key,
            false
          ));
                                          accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = RemoveCronTransactionV0InstructionData::new().try_to_vec().unwrap();
          let mut args = self.__args.try_to_vec().unwrap();
      data.append(&mut args);
    
    let instruction = solana_instruction::Instruction {
      program_id: crate::cron_client::CRON_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(6 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.rent_refund.clone());
                        account_infos.push(self.authority.clone());
                        account_infos.push(self.cron_job.clone());
                        account_infos.push(self.cron_job_transaction.clone());
                        account_infos.push(self.system_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_cpi::invoke(&instruction, &account_infos)
    } else {
      solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `RemoveCronTransactionV0` via CPI.
///
/// ### Accounts:
///
                      ///   0. `[writable, signer]` rent_refund
                ///   1. `[signer]` authority
                ///   2. `[writable]` cron_job
                ///   3. `[writable]` cron_job_transaction
          ///   4. `[]` system_program
#[derive(Clone, Debug)]
pub struct RemoveCronTransactionV0CpiBuilder<'a, 'b> {
  instruction: Box<RemoveCronTransactionV0CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> RemoveCronTransactionV0CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(RemoveCronTransactionV0CpiBuilderInstruction {
      __program: program,
              rent_refund: None,
              authority: None,
              cron_job: None,
              cron_job_transaction: None,
              system_program: None,
                                            index: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn rent_refund(&mut self, rent_refund: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.rent_refund = Some(rent_refund);
                    self
    }
      #[inline(always)]
    pub fn authority(&mut self, authority: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.authority = Some(authority);
                    self
    }
      #[inline(always)]
    pub fn cron_job(&mut self, cron_job: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job = Some(cron_job);
                    self
    }
      #[inline(always)]
    pub fn cron_job_transaction(&mut self, cron_job_transaction: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.cron_job_transaction = Some(cron_job_transaction);
                    self
    }
      #[inline(always)]
    pub fn system_program(&mut self, system_program: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.system_program = Some(system_program);
                    self
    }
                    #[inline(always)]
      pub fn index(&mut self, index: u32) -> &mut Self {
        self.instruction.index = Some(index);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program_error::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
          let args = RemoveCronTransactionV0InstructionArgs {
                                                              index: self.instruction.index.clone().expect("index is not set"),
                                    };
        let instruction = RemoveCronTransactionV0Cpi {
        __program: self.instruction.__program,
                  
          rent_refund: self.instruction.rent_refund.expect("rent_refund is not set"),
                  
          authority: self.instruction.authority.expect("authority is not set"),
                  
          cron_job: self.instruction.cron_job.expect("cron_job is not set"),
                  
          cron_job_transaction: self.instruction.cron_job_transaction.expect("cron_job_transaction is not set"),
                  
          system_program: self.instruction.system_program.expect("system_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct RemoveCronTransactionV0CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_account_info::AccountInfo<'a>,
            rent_refund: Option<&'b solana_account_info::AccountInfo<'a>>,
                authority: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job: Option<&'b solana_account_info::AccountInfo<'a>>,
                cron_job_transaction: Option<&'b solana_account_info::AccountInfo<'a>>,
                system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
                        index: Option<u32>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}

