//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::tuktuk_client::types::CompiledTransactionV0;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct RemoteTaskTransactionV0 {
pub discriminator: [u8; 8],
pub verification_hash: [u8; 32],
pub transaction: CompiledTransactionV0,
}


pub const REMOTE_TASK_TRANSACTION_V0_DISCRIMINATOR: [u8; 8] = [244, 225, 238, 116, 199, 12, 9, 191];

impl RemoteTaskTransactionV0 {
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for RemoteTaskTransactionV0 {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_remote_task_transaction_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::DecodedAccount<RemoteTaskTransactionV0>, std::io::Error> {
  let accounts = fetch_all_remote_task_transaction_v0(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_remote_task_transaction_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::DecodedAccount<RemoteTaskTransactionV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::DecodedAccount<RemoteTaskTransactionV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::other(format!("Account not found: {address}")))?;
      let data = RemoteTaskTransactionV0::from_bytes(&account.data)?;
      decoded_accounts.push(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_remote_task_transaction_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::MaybeAccount<RemoteTaskTransactionV0>, std::io::Error> {
    let accounts = fetch_all_maybe_remote_task_transaction_v0(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_remote_task_transaction_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::MaybeAccount<RemoteTaskTransactionV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::MaybeAccount<RemoteTaskTransactionV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = RemoteTaskTransactionV0::from_bytes(&account.data)?;
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::Exists(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for RemoteTaskTransactionV0 {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for RemoteTaskTransactionV0 {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for RemoteTaskTransactionV0 {
      fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(
          crate::tuktuk_client::TUKTUK_ID.to_bytes()
        )
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for RemoteTaskTransactionV0 {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for RemoteTaskTransactionV0 {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

