//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::Address;
use crate::tuktuk_client::types::TriggerV0;
use crate::tuktuk_client::types::TransactionSourceV0;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct TaskV0 {
pub discriminator: [u8; 8],
pub task_queue: Address,
pub rent_amount: u64,
pub crank_reward: u64,
pub id: u16,
pub trigger: TriggerV0,
pub rent_refund: Address,
pub transaction: TransactionSourceV0,
pub queued_at: i64,
pub bump_seed: u8,
pub free_tasks: u8,
pub description: String,
}


pub const TASK_V0_DISCRIMINATOR: [u8; 8] = [242, 93, 213, 169, 42, 94, 239, 80];

impl TaskV0 {
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for TaskV0 {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_task_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::DecodedAccount<TaskV0>, std::io::Error> {
  let accounts = fetch_all_task_v0(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_task_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::DecodedAccount<TaskV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::DecodedAccount<TaskV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::other(format!("Account not found: {address}")))?;
      let data = TaskV0::from_bytes(&account.data)?;
      decoded_accounts.push(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_task_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::MaybeAccount<TaskV0>, std::io::Error> {
    let accounts = fetch_all_maybe_task_v0(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_task_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::MaybeAccount<TaskV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::MaybeAccount<TaskV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = TaskV0::from_bytes(&account.data)?;
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::Exists(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for TaskV0 {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for TaskV0 {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for TaskV0 {
      fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(
          crate::tuktuk_client::TUKTUK_ID.to_bytes()
        )
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for TaskV0 {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for TaskV0 {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

