//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use solana_address::Address;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;


#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
pub struct TaskQueueV0 {
pub discriminator: [u8; 8],
pub tuktuk_config: Address,
pub id: u32,
pub update_authority: Address,
pub reserved: Address,
pub min_crank_reward: u64,
pub uncollected_protocol_fees: u64,
pub capacity: u16,
pub created_at: i64,
pub updated_at: i64,
pub bump_seed: u8,
pub task_bitmap: Vec<u8>,
pub name: String,
pub lookup_tables: Vec<Address>,
pub num_queue_authorities: u16,
pub stale_task_age: u32,
}


pub const TASK_QUEUE_V0_DISCRIMINATOR: [u8; 8] = [150, 24, 232, 159, 105, 32, 161, 17];

impl TaskQueueV0 {
  
  
  
  #[inline(always)]
  pub fn from_bytes(data: &[u8]) -> Result<Self, std::io::Error> {
    let mut data = data;
    Self::deserialize(&mut data)
  }
}

impl<'a> TryFrom<&solana_account_info::AccountInfo<'a>> for TaskQueueV0 {
  type Error = std::io::Error;

  fn try_from(account_info: &solana_account_info::AccountInfo<'a>) -> Result<Self, Self::Error> {
      let mut data: &[u8] = &(*account_info.data).borrow();
      Self::deserialize(&mut data)
  }
}

#[cfg(feature = "fetch")]
pub fn fetch_task_queue_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::DecodedAccount<TaskQueueV0>, std::io::Error> {
  let accounts = fetch_all_task_queue_v0(rpc, &[*address])?;
  Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_task_queue_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::DecodedAccount<TaskQueueV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::DecodedAccount<TaskQueueV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      let account = accounts[i].as_ref()
        .ok_or(std::io::Error::other(format!("Account not found: {address}")))?;
      let data = TaskQueueV0::from_bytes(&account.data)?;
      decoded_accounts.push(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data });
    }
    Ok(decoded_accounts)
}

#[cfg(feature = "fetch")]
pub fn fetch_maybe_task_queue_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  address: &solana_address::Address,
) -> Result<crate::tuktuk_client::shared::MaybeAccount<TaskQueueV0>, std::io::Error> {
    let accounts = fetch_all_maybe_task_queue_v0(rpc, &[*address])?;
    Ok(accounts[0].clone())
}

#[cfg(feature = "fetch")]
pub fn fetch_all_maybe_task_queue_v0(
  rpc: &solana_rpc_client::rpc_client::RpcClient,
  addresses: &[solana_address::Address],
) -> Result<Vec<crate::tuktuk_client::shared::MaybeAccount<TaskQueueV0>>, std::io::Error> {
    let accounts = rpc.get_multiple_accounts(addresses)
      .map_err(|e| std::io::Error::other(e.to_string()))?;
    let mut decoded_accounts: Vec<crate::tuktuk_client::shared::MaybeAccount<TaskQueueV0>> = Vec::new();
    for i in 0..addresses.len() {
      let address = addresses[i];
      if let Some(account) = accounts[i].as_ref() {
        let data = TaskQueueV0::from_bytes(&account.data)?;
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::Exists(crate::tuktuk_client::shared::DecodedAccount { address, account: account.clone(), data }));
      } else {
        decoded_accounts.push(crate::tuktuk_client::shared::MaybeAccount::NotFound(address));
      }
    }
  Ok(decoded_accounts)
}

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountDeserialize for TaskQueueV0 {
      fn try_deserialize_unchecked(buf: &mut &[u8]) -> anchor_lang::Result<Self> {
        Ok(Self::deserialize(buf)?)
      }
  }

  #[cfg(feature = "anchor")]
  impl anchor_lang::AccountSerialize for TaskQueueV0 {}

  #[cfg(feature = "anchor")]
  impl anchor_lang::Owner for TaskQueueV0 {
      fn owner() -> anchor_lang::solana_program::pubkey::Pubkey {
        anchor_lang::solana_program::pubkey::Pubkey::from(
          crate::tuktuk_client::TUKTUK_ID.to_bytes()
        )
      }
  }

  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::IdlBuild for TaskQueueV0 {}

  
  #[cfg(feature = "anchor-idl-build")]
  impl anchor_lang::Discriminator for TaskQueueV0 {
    const DISCRIMINATOR: &[u8] = &[0; 8];
  }

